import 'layer_recipe.dart';

class WaveScreenDefaults {
  static const List<WaveScreenLayer> layers = [
    WaveScreenLayer(
      zIndex: 0,
      recipe: WaveLayerRecipe(
        amplitudeMin: 6,
        amplitudeMax: 10,
        frequencyMin: 0.44,
        frequencyMax: 0.58,
        speedMin: 0.16,
        speedMax: 0.22,
        placement: WavePlacement(0.02, 0.06),
        slopeMin: -0.16,
        slopeMax: -0.10,
        horizontalShiftMin: -0.26,
        horizontalShiftMax: -0.06,
        secondaryStrengthMin: 0.03,
        secondaryStrengthMax: 0.08,
      ),
    ),
    WaveScreenLayer(
      zIndex: 1,
      recipe: WaveLayerRecipe(
        amplitudeMin: 10,
        amplitudeMax: 16,
        frequencyMin: 0.60,
        frequencyMax: 0.74,
        speedMin: -0.22,
        speedMax: -0.15,
        placement: WavePlacement(0.10, 0.16),
        slopeMin: 0.06,
        slopeMax: 0.12,
        horizontalShiftMin: 0.10,
        horizontalShiftMax: 0.24,
        secondaryStrengthMin: 0.06,
        secondaryStrengthMax: 0.12,
      ),
    ),
    WaveScreenLayer(
      zIndex: 2,
      recipe: WaveLayerRecipe(
        amplitudeMin: 12,
        amplitudeMax: 18,
        frequencyMin: 0.68,
        frequencyMax: 0.82,
        speedMin: 0.10,
        speedMax: 0.18,
        placement: WavePlacement(0.20, 0.27),
        slopeMin: -0.14,
        slopeMax: -0.06,
        horizontalShiftMin: -0.18,
        horizontalShiftMax: 0.00,
        secondaryStrengthMin: 0.10,
        secondaryStrengthMax: 0.16,
      ),
    ),
    WaveScreenLayer(
      zIndex: 3,
      recipe: WaveLayerRecipe(
        amplitudeMin: 18,
        amplitudeMax: 24,
        frequencyMin: 0.76,
        frequencyMax: 0.92,
        speedMin: -0.18,
        speedMax: -0.10,
        placement: WavePlacement(0.30, 0.36),
        slopeMin: 0.10,
        slopeMax: 0.18,
        horizontalShiftMin: 0.12,
        horizontalShiftMax: 0.26,
        secondaryStrengthMin: 0.13,
        secondaryStrengthMax: 0.20,
      ),
    ),
    WaveScreenLayer(
      zIndex: 4,
      recipe: WaveLayerRecipe(
        amplitudeMin: 22,
        amplitudeMax: 30,
        frequencyMin: 0.72,
        frequencyMax: 0.88,
        speedMin: 0.08,
        speedMax: 0.15,
        placement: WavePlacement(0.40, 0.47),
        slopeMin: -0.12,
        slopeMax: -0.04,
        horizontalShiftMin: -0.24,
        horizontalShiftMax: -0.08,
        secondaryStrengthMin: 0.14,
        secondaryStrengthMax: 0.22,
      ),
    ),
    WaveScreenLayer(
      zIndex: 5,
      recipe: WaveLayerRecipe(
        amplitudeMin: 20,
        amplitudeMax: 28,
        frequencyMin: 0.86,
        frequencyMax: 1.00,
        speedMin: -0.12,
        speedMax: -0.05,
        placement: WavePlacement(0.50, 0.57),
        slopeMin: 0.02,
        slopeMax: 0.10,
        horizontalShiftMin: 0.02,
        horizontalShiftMax: 0.18,
        secondaryStrengthMin: 0.15,
        secondaryStrengthMax: 0.23,
      ),
    ),
    WaveScreenLayer(
      zIndex: 6,
      recipe: WaveLayerRecipe(
        amplitudeMin: 26,
        amplitudeMax: 34,
        frequencyMin: 0.78,
        frequencyMax: 0.92,
        speedMin: 0.07,
        speedMax: 0.13,
        placement: WavePlacement(0.60, 0.67),
        slopeMin: -0.16,
        slopeMax: -0.08,
        horizontalShiftMin: -0.22,
        horizontalShiftMax: -0.04,
        secondaryStrengthMin: 0.12,
        secondaryStrengthMax: 0.20,
      ),
    ),
    WaveScreenLayer(
      zIndex: 7,
      recipe: WaveLayerRecipe(
        amplitudeMin: 18,
        amplitudeMax: 26,
        frequencyMin: 0.94,
        frequencyMax: 1.08,
        speedMin: -0.10,
        speedMax: -0.04,
        placement: WavePlacement(0.69, 0.75),
        slopeMin: 0.08,
        slopeMax: 0.16,
        horizontalShiftMin: 0.08,
        horizontalShiftMax: 0.24,
        secondaryStrengthMin: 0.14,
        secondaryStrengthMax: 0.22,
      ),
    ),
    WaveScreenLayer(
      zIndex: 8,
      recipe: WaveLayerRecipe(
        amplitudeMin: 28,
        amplitudeMax: 38,
        frequencyMin: 0.82,
        frequencyMax: 0.96,
        speedMin: 0.05,
        speedMax: 0.10,
        placement: WavePlacement(0.77, 0.83),
        slopeMin: -0.12,
        slopeMax: -0.02,
        horizontalShiftMin: -0.20,
        horizontalShiftMax: -0.02,
        secondaryStrengthMin: 0.12,
        secondaryStrengthMax: 0.20,
      ),
    ),
    WaveScreenLayer(
      zIndex: 9,
      recipe: WaveLayerRecipe(
        amplitudeMin: 16,
        amplitudeMax: 24,
        frequencyMin: 1.02,
        frequencyMax: 1.16,
        speedMin: -0.08,
        speedMax: -0.03,
        placement: WavePlacement(0.84, 0.89),
        slopeMin: 0.06,
        slopeMax: 0.12,
        horizontalShiftMin: 0.00,
        horizontalShiftMax: 0.14,
        secondaryStrengthMin: 0.16,
        secondaryStrengthMax: 0.24,
      ),
    ),
    WaveScreenLayer(
      zIndex: 10,
      recipe: WaveLayerRecipe(
        amplitudeMin: 12,
        amplitudeMax: 20,
        frequencyMin: 1.08,
        frequencyMax: 1.22,
        speedMin: -0.06,
        speedMax: -0.02,
        placement: WavePlacement(0.90, 0.95),
        slopeMin: -0.08,
        slopeMax: 0.02,
        horizontalShiftMin: -0.12,
        horizontalShiftMax: 0.08,
        secondaryStrengthMin: 0.18,
        secondaryStrengthMax: 0.26,
        blur: true,
      ),
    ),
  ];
}